### PR TITLE
Fix pip install bug

### PR DESCRIPTION
**Pull request by RNogales94**
When I've tried to make pip directly from your git repository I've found a `str - const char []` casting error.

I've solved it, forcing the casting to string in Python before go Cython, I think is a easy and clean way to do it.

I hope this help, more people

### CODE REVIEW

**Comment by alwc** [comment]
Hi @RNogales94 , which protobuf version are you using? I tried to install `cld3` with

```bash
 pip install git+https://github.com/RNogales94/cld3  
```
but I'm getting the following error:

```bash
Collecting git+https://github.com/RNogales94/cld3
  Cloning https://github.com/RNogales94/cld3 to /tmp/pip-req-build-qbd0f18m
Building wheels for collected packages: cld3
  Running setup.py bdist_wheel for cld3 ... error
  Complete output from command /opt/conda/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-qbd0f18m/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-wq46zt5u --python-tag cp36:
  running bdist_wheel
  running build
  running build_ext
  building 'cld3' extension
  creating build
  creating build/temp.linux-x86_64-3.6
  creating build/temp.linux-x86_64-3.6/src
  creating build/temp.linux-x86_64-3.6/src/cld_3
  creating build/temp.linux-x86_64-3.6/src/cld_3/protos
  creating build/temp.linux-x86_64-3.6/src/cld_3/protos/src
  creating build/temp.linux-x86_64-3.6/src/script_span
  gcc -pthread -B /opt/conda/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Isrc -I./src -I./src/cld_3/protos/ -I/opt/conda/include/python3.6m -c src/cld3.cpp -o build/temp.linux-x86_64-3.6/src/cld3.o -std=c++11
  cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
  In file included from src/feature_extractor.h:45:0,
                   from src/embedding_feature_extractor.h:23,
                   from src/nnet_language_identifier.h:22,
                   from src/cld3.cpp:683:
  src/cld_3/protos/src/feature_extractor.pb.h:12:2: error: #error This file was generated by a newer version of protoc which is
   #error This file was generated by a newer version of protoc which is
    ^~~~~
  src/cld_3/protos/src/feature_extractor.pb.h:13:2: error: #error incompatible with your Protocol Buffer headers. Please update
   #error incompatible with your Protocol Buffer headers.  Please update
    ^~~~~
  src/cld_3/protos/src/feature_extractor.pb.h:14:2: error: #error your headers.
   #error your headers.
    ^~~~~
  In file included from src/feature_extractor.h:45:0,
                   from src/embedding_feature_extractor.h:23,
                   from src/nnet_language_identifier.h:22,
                   from src/cld3.cpp:683:
  src/cld_3/protos/src/feature_extractor.pb.h:23:35: fatal error: google/protobuf/arena.h: No such file or directory
   #include <google/protobuf/arena.h>
                                     ^
  compilation terminated.
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for cld3
  Running setup.py clean for cld3
```

**Comment by alwc** [comment]
Things work properly when I build protobuf from source.

**Comment by bact** [comment]
This fix works well for me on python:3.7-alpine Docker image, with protobuf and protobuf-dev packages installed.

**Comment by Elizafox** [comment]
Thanks 👍

**Pull request merged**
